services:
  hippo-bpm-web:
    build: .
    container_name: hippo-bpm
    ports:
      - "8080:8080"
    volumes:
      - hippo-bpm-data:/usr/src/app/database.sqlite
    environment:
      - NODE_ENV=production

volumes:
  hippo-bpm-data: